services:
  collector:
    image: otel/opentelemetry-collector:latest
    restart: unless-stopped
    command: --config=/etc/otelcol/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./collector/config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true