services:
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tunnel/hosts:/etc/hosts
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    command: --config=/etc/otelcol/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./collector/config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ${DATA_DIR:-./data}/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ${DATA_DIR:-./data}/grafana:/var/lib/grafana
    depends_on:
      - clickhouse