services:
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tunnel/hosts:/etc/hosts
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector:latest
    restart: unless-stopped
    command: --config=/etc/otelcol/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./collector/config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command: --config.file=/etc/prometheus/config.yaml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus/config.yaml
    depends_on:
      - collector

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
      - jaeger