apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: default
      defaultDatabase: otel
    secureJsonData:
      password: $__env{CLICKHOUSE_PASSWORD}
